"""ref models

Revision ID: 1fee3f605dfa
Revises: 2b0b36c13cde
Create Date: 2022-10-16 20:59:22.616124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fee3f605dfa'
down_revision = '2b0b36c13cde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
