"""migration1

Revision ID: 2b0b36c13cde
Revises: ccd25b7ea29b
Create Date: 2022-10-16 20:29:27.943741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0b36c13cde'
down_revision = 'ccd25b7ea29b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
