"""First migration

Revision ID: ccd25b7ea29b
Revises: 962b7d2d5097
Create Date: 2022-10-14 16:08:00.798332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd25b7ea29b'
down_revision = '962b7d2d5097'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
